[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["src/views/**", "src/public/**"]

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/index"
